name: Docker Imaj CI

env:
  GHCR: ghcr.io
  DOCKER: docker.io
  IMAJ_ADI: samba

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 22 1 * *" # Her ayın ilk günü saat 22:00'de çalışacak

jobs:
  guvenlik-taramasi:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Kontrol Et
        uses: actions/checkout@v4

      - name: Güvenlik Taraması Yap
        uses: ShiftLeftSecurity/scan-action@master

  imaj-olustur-ve-yukle:
    runs-on: ubuntu-latest
    needs:
      - guvenlik-taramasi
    steps:
      - name: Kodu Kontrol Et
        uses: actions/checkout@v4

      - name: QEMU Kurulumu
        uses: docker/setup-qemu-action@v3

      - name: Docker Buildx Kurulumu
        uses: docker/setup-buildx-action@v3

      - name: Github Container Registry'ye Giriş Yap
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Hub'a Giriş Yap
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Mevcut Tarihi Al
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Oluştur ve Yükle
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.GHCR }}/${{ github.repository_owner }}/${{ env.IMAJ_ADI }}:latest
            ${{ env.GHCR }}/${{ github.repository_owner }}/${{ env.IMAJ_ADI }}:${{ steps.date.outputs.date }}
            ${{ env.DOCKER }}/${{ github.repository_owner }}/${{ env.IMAJ_ADI }}:latest
            ${{ env.DOCKER }}/${{ github.repository_owner }}/${{ env.IMAJ_ADI }}:${{ steps.date.outputs.date }}

      - name: Docker Hub'a README.md Gönder
        uses: peter-evans/dockerhub-description@v4
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAJ_ADI }}
            short-description: ${{ github.event.repository.description }}
            readme-filepath: ./README.md

  imaj-guvenlik-taramasi:
    runs-on: ubuntu-latest
    needs: imaj-olustur-ve-yukle
    steps:
      - name: Trivy Güvenlik Tarayıcısı Çalıştır
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.GHCR }}/${{ github.repository_owner }}/${{ env.IMAJ_ADI }}:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
